[package]
name = "zlayer-overlay"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "WireGuard-based encrypted overlay networking for containers"
keywords = ["container", "networking", "wireguard", "overlay", "mesh"]
categories = ["network-programming"]
readme = "README.md"

[dependencies]
blake2.workspace = true
ipnet = "2.10"
serde.workspace = true
serde_json.workspace = true
zlayer-spec = { version = "0.1.0", path = "../zlayer-spec" }
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
trust-dns-client.workspace = true
trust-dns-server.workspace = true
x25519-dalek.workspace = true
zlayer-core = { version = "0.1.0", path = "../zlayer-core" }
base64.workspace = true
rand.workspace = true
